version: '3.1'
services:

    # Application container
    dotnet:
        image: microsoft/dotnet
        environment:
          PORT: 8080
        volumes:
          - ./:/server/http
        links:
            - mongodb
        ports:
          - "8080:8080"

   
    mongodb:
        image: mongo
        restart: unless-stopped
        ports:
            - "27017"

           

   